// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: internal/protobuf/db/db.proto

package db

import (
	any "github.com/golang/protobuf/ptypes/any"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SQLJoin_JoinType int32

const (
	SQLJoin_IN  SQLJoin_JoinType = 0
	SQLJoin_LO  SQLJoin_JoinType = 1
	SQLJoin_RO  SQLJoin_JoinType = 2
	SQLJoin_OUT SQLJoin_JoinType = 3
)

// Enum value maps for SQLJoin_JoinType.
var (
	SQLJoin_JoinType_name = map[int32]string{
		0: "IN",
		1: "LO",
		2: "RO",
		3: "OUT",
	}
	SQLJoin_JoinType_value = map[string]int32{
		"IN":  0,
		"LO":  1,
		"RO":  2,
		"OUT": 3,
	}
)

func (x SQLJoin_JoinType) Enum() *SQLJoin_JoinType {
	p := new(SQLJoin_JoinType)
	*p = x
	return p
}

func (x SQLJoin_JoinType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SQLJoin_JoinType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_protobuf_db_db_proto_enumTypes[0].Descriptor()
}

func (SQLJoin_JoinType) Type() protoreflect.EnumType {
	return &file_internal_protobuf_db_db_proto_enumTypes[0]
}

func (x SQLJoin_JoinType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SQLJoin_JoinType.Descriptor instead.
func (SQLJoin_JoinType) EnumDescriptor() ([]byte, []int) {
	return file_internal_protobuf_db_db_proto_rawDescGZIP(), []int{1, 0}
}

type SQLResult_Result int32

const (
	SQLResult_CREATE SQLResult_Result = 0
	SQLResult_UPDATE SQLResult_Result = 1
	SQLResult_DELETE SQLResult_Result = 2
	SQLResult_SELECT SQLResult_Result = 3
)

// Enum value maps for SQLResult_Result.
var (
	SQLResult_Result_name = map[int32]string{
		0: "CREATE",
		1: "UPDATE",
		2: "DELETE",
		3: "SELECT",
	}
	SQLResult_Result_value = map[string]int32{
		"CREATE": 0,
		"UPDATE": 1,
		"DELETE": 2,
		"SELECT": 3,
	}
)

func (x SQLResult_Result) Enum() *SQLResult_Result {
	p := new(SQLResult_Result)
	*p = x
	return p
}

func (x SQLResult_Result) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SQLResult_Result) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_protobuf_db_db_proto_enumTypes[1].Descriptor()
}

func (SQLResult_Result) Type() protoreflect.EnumType {
	return &file_internal_protobuf_db_db_proto_enumTypes[1]
}

func (x SQLResult_Result) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SQLResult_Result.Descriptor instead.
func (SQLResult_Result) EnumDescriptor() ([]byte, []int) {
	return file_internal_protobuf_db_db_proto_rawDescGZIP(), []int{2, 0}
}

type SQLOption struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Where string     `protobuf:"bytes,1,opt,name=where,proto3" json:"where,omitempty"`
	Order string     `protobuf:"bytes,2,opt,name=order,proto3" json:"order,omitempty"`
	Limit string     `protobuf:"bytes,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Args  []*any.Any `protobuf:"bytes,4,rep,name=args,proto3" json:"args,omitempty"`
}

func (x *SQLOption) Reset() {
	*x = SQLOption{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protobuf_db_db_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SQLOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SQLOption) ProtoMessage() {}

func (x *SQLOption) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_db_db_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SQLOption.ProtoReflect.Descriptor instead.
func (*SQLOption) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_db_db_proto_rawDescGZIP(), []int{0}
}

func (x *SQLOption) GetWhere() string {
	if x != nil {
		return x.Where
	}
	return ""
}

func (x *SQLOption) GetOrder() string {
	if x != nil {
		return x.Order
	}
	return ""
}

func (x *SQLOption) GetLimit() string {
	if x != nil {
		return x.Limit
	}
	return ""
}

func (x *SQLOption) GetArgs() []*any.Any {
	if x != nil {
		return x.Args
	}
	return nil
}

type SQLJoin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JoinType     SQLJoin_JoinType `protobuf:"varint,1,opt,name=joinType,proto3,enum=db.SQLJoin_JoinType" json:"joinType,omitempty"`
	JoinTable    string           `protobuf:"bytes,2,opt,name=joinTable,proto3" json:"joinTable,omitempty"`
	Intersection string           `protobuf:"bytes,3,opt,name=intersection,proto3" json:"intersection,omitempty"`
	Args         []*any.Any       `protobuf:"bytes,4,rep,name=args,proto3" json:"args,omitempty"`
}

func (x *SQLJoin) Reset() {
	*x = SQLJoin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protobuf_db_db_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SQLJoin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SQLJoin) ProtoMessage() {}

func (x *SQLJoin) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_db_db_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SQLJoin.ProtoReflect.Descriptor instead.
func (*SQLJoin) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_db_db_proto_rawDescGZIP(), []int{1}
}

func (x *SQLJoin) GetJoinType() SQLJoin_JoinType {
	if x != nil {
		return x.JoinType
	}
	return SQLJoin_IN
}

func (x *SQLJoin) GetJoinTable() string {
	if x != nil {
		return x.JoinTable
	}
	return ""
}

func (x *SQLJoin) GetIntersection() string {
	if x != nil {
		return x.Intersection
	}
	return ""
}

func (x *SQLJoin) GetArgs() []*any.Any {
	if x != nil {
		return x.Args
	}
	return nil
}

type SQLResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result SQLResult_Result `protobuf:"varint,1,opt,name=result,proto3,enum=db.SQLResult_Result" json:"result,omitempty"`
	Data   []*any.Any       `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *SQLResult) Reset() {
	*x = SQLResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protobuf_db_db_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SQLResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SQLResult) ProtoMessage() {}

func (x *SQLResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_db_db_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SQLResult.ProtoReflect.Descriptor instead.
func (*SQLResult) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_db_db_proto_rawDescGZIP(), []int{2}
}

func (x *SQLResult) GetResult() SQLResult_Result {
	if x != nil {
		return x.Result
	}
	return SQLResult_CREATE
}

func (x *SQLResult) GetData() []*any.Any {
	if x != nil {
		return x.Data
	}
	return nil
}

type SQLInsertParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Table  string     `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	Datas  string     `protobuf:"bytes,2,opt,name=datas,proto3" json:"datas,omitempty"`
	Values []*any.Any `protobuf:"bytes,3,rep,name=values,proto3" json:"values,omitempty"`
}

func (x *SQLInsertParams) Reset() {
	*x = SQLInsertParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protobuf_db_db_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SQLInsertParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SQLInsertParams) ProtoMessage() {}

func (x *SQLInsertParams) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_db_db_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SQLInsertParams.ProtoReflect.Descriptor instead.
func (*SQLInsertParams) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_db_db_proto_rawDescGZIP(), []int{3}
}

func (x *SQLInsertParams) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *SQLInsertParams) GetDatas() string {
	if x != nil {
		return x.Datas
	}
	return ""
}

func (x *SQLInsertParams) GetValues() []*any.Any {
	if x != nil {
		return x.Values
	}
	return nil
}

type SQLUpdateParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Table   string            `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	Couples map[string]string `protobuf:"bytes,2,rep,name=couples,proto3" json:"couples,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Options *SQLOption        `protobuf:"bytes,3,opt,name=options,proto3" json:"options,omitempty"`
}

func (x *SQLUpdateParams) Reset() {
	*x = SQLUpdateParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protobuf_db_db_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SQLUpdateParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SQLUpdateParams) ProtoMessage() {}

func (x *SQLUpdateParams) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_db_db_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SQLUpdateParams.ProtoReflect.Descriptor instead.
func (*SQLUpdateParams) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_db_db_proto_rawDescGZIP(), []int{4}
}

func (x *SQLUpdateParams) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *SQLUpdateParams) GetCouples() map[string]string {
	if x != nil {
		return x.Couples
	}
	return nil
}

func (x *SQLUpdateParams) GetOptions() *SQLOption {
	if x != nil {
		return x.Options
	}
	return nil
}

type SQLDeleteParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Table   string     `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	Options *SQLOption `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
}

func (x *SQLDeleteParams) Reset() {
	*x = SQLDeleteParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protobuf_db_db_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SQLDeleteParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SQLDeleteParams) ProtoMessage() {}

func (x *SQLDeleteParams) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_db_db_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SQLDeleteParams.ProtoReflect.Descriptor instead.
func (*SQLDeleteParams) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_db_db_proto_rawDescGZIP(), []int{5}
}

func (x *SQLDeleteParams) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *SQLDeleteParams) GetOptions() *SQLOption {
	if x != nil {
		return x.Options
	}
	return nil
}

type SQLSelectParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	What    string     `protobuf:"bytes,1,opt,name=what,proto3" json:"what,omitempty"`
	Table   string     `protobuf:"bytes,2,opt,name=table,proto3" json:"table,omitempty"`
	Options *SQLOption `protobuf:"bytes,3,opt,name=options,proto3" json:"options,omitempty"`
	Joins   []*SQLJoin `protobuf:"bytes,4,rep,name=joins,proto3" json:"joins,omitempty"`
	Args    []*any.Any `protobuf:"bytes,5,rep,name=args,proto3" json:"args,omitempty"`
}

func (x *SQLSelectParams) Reset() {
	*x = SQLSelectParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protobuf_db_db_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SQLSelectParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SQLSelectParams) ProtoMessage() {}

func (x *SQLSelectParams) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_db_db_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SQLSelectParams.ProtoReflect.Descriptor instead.
func (*SQLSelectParams) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_db_db_proto_rawDescGZIP(), []int{6}
}

func (x *SQLSelectParams) GetWhat() string {
	if x != nil {
		return x.What
	}
	return ""
}

func (x *SQLSelectParams) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *SQLSelectParams) GetOptions() *SQLOption {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *SQLSelectParams) GetJoins() []*SQLJoin {
	if x != nil {
		return x.Joins
	}
	return nil
}

func (x *SQLSelectParams) GetArgs() []*any.Any {
	if x != nil {
		return x.Args
	}
	return nil
}

var File_internal_protobuf_db_db_proto protoreflect.FileDescriptor

var file_internal_protobuf_db_db_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x64, 0x62, 0x2f, 0x64, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x02, 0x64, 0x62, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x77,
	0x0a, 0x09, 0x53, 0x51, 0x4c, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x77,
	0x68, 0x65, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x77, 0x68, 0x65, 0x72,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x28, 0x0a,
	0x04, 0x61, 0x72, 0x67, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e,
	0x79, 0x52, 0x04, 0x61, 0x72, 0x67, 0x73, 0x22, 0xd4, 0x01, 0x0a, 0x07, 0x53, 0x51, 0x4c, 0x4a,
	0x6f, 0x69, 0x6e, 0x12, 0x30, 0x0a, 0x08, 0x6a, 0x6f, 0x69, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x64, 0x62, 0x2e, 0x53, 0x51, 0x4c, 0x4a, 0x6f,
	0x69, 0x6e, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x6a, 0x6f, 0x69,
	0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6a, 0x6f, 0x69, 0x6e, 0x54, 0x61, 0x62,
	0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6a, 0x6f, 0x69, 0x6e, 0x54, 0x61,
	0x62, 0x6c, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x73, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x73, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x28, 0x0a, 0x04, 0x61, 0x72, 0x67, 0x73, 0x18,
	0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x04, 0x61, 0x72, 0x67,
	0x73, 0x22, 0x2b, 0x0a, 0x08, 0x4a, 0x6f, 0x69, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x06, 0x0a,
	0x02, 0x49, 0x4e, 0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x4c, 0x4f, 0x10, 0x01, 0x12, 0x06, 0x0a,
	0x02, 0x52, 0x4f, 0x10, 0x02, 0x12, 0x07, 0x0a, 0x03, 0x4f, 0x55, 0x54, 0x10, 0x03, 0x22, 0x9d,
	0x01, 0x0a, 0x09, 0x53, 0x51, 0x4c, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x2c, 0x0a, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x64,
	0x62, 0x2e, 0x53, 0x51, 0x4c, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x2e, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x28, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x22, 0x38, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x0a,
	0x0a, 0x06, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x55, 0x50,
	0x44, 0x41, 0x54, 0x45, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x44, 0x45, 0x4c, 0x45, 0x54, 0x45,
	0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x45, 0x4c, 0x45, 0x43, 0x54, 0x10, 0x03, 0x22, 0x6b,
	0x0a, 0x0f, 0x53, 0x51, 0x4c, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d,
	0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x64, 0x61, 0x74, 0x61, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x64, 0x61, 0x74, 0x61, 0x73, 0x12, 0x2c, 0x0a,
	0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x41, 0x6e, 0x79, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22, 0xc8, 0x01, 0x0a, 0x0f,
	0x53, 0x51, 0x4c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x3a, 0x0a, 0x07, 0x63, 0x6f, 0x75, 0x70, 0x6c, 0x65, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x64, 0x62, 0x2e, 0x53, 0x51, 0x4c, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x2e, 0x43, 0x6f, 0x75, 0x70,
	0x6c, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x63, 0x6f, 0x75, 0x70, 0x6c, 0x65,
	0x73, 0x12, 0x27, 0x0a, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x64, 0x62, 0x2e, 0x53, 0x51, 0x4c, 0x4f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x1a, 0x3a, 0x0a, 0x0c, 0x43, 0x6f,
	0x75, 0x70, 0x6c, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x50, 0x0a, 0x0f, 0x53, 0x51, 0x4c, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x61, 0x62,
	0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x12,
	0x27, 0x0a, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0d, 0x2e, 0x64, 0x62, 0x2e, 0x53, 0x51, 0x4c, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0xb1, 0x01, 0x0a, 0x0f, 0x53, 0x51, 0x4c,
	0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x12, 0x0a, 0x04,
	0x77, 0x68, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x77, 0x68, 0x61, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x27, 0x0a, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x64, 0x62, 0x2e, 0x53, 0x51, 0x4c,
	0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12,
	0x21, 0x0a, 0x05, 0x6a, 0x6f, 0x69, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b,
	0x2e, 0x64, 0x62, 0x2e, 0x53, 0x51, 0x4c, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x05, 0x6a, 0x6f, 0x69,
	0x6e, 0x73, 0x12, 0x28, 0x0a, 0x04, 0x61, 0x72, 0x67, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x04, 0x61, 0x72, 0x67, 0x73, 0x32, 0xbc, 0x01, 0x0a,
	0x02, 0x44, 0x42, 0x12, 0x2c, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x13, 0x2e,
	0x64, 0x62, 0x2e, 0x53, 0x51, 0x4c, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x73, 0x1a, 0x0d, 0x2e, 0x64, 0x62, 0x2e, 0x53, 0x51, 0x4c, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x12, 0x2c, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x13, 0x2e, 0x64, 0x62,
	0x2e, 0x53, 0x51, 0x4c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73,
	0x1a, 0x0d, 0x2e, 0x64, 0x62, 0x2e, 0x53, 0x51, 0x4c, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12,
	0x2c, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x13, 0x2e, 0x64, 0x62, 0x2e, 0x53,
	0x51, 0x4c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x1a, 0x0d,
	0x2e, 0x64, 0x62, 0x2e, 0x53, 0x51, 0x4c, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x2c, 0x0a,
	0x06, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x12, 0x13, 0x2e, 0x64, 0x62, 0x2e, 0x53, 0x51, 0x4c,
	0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x1a, 0x0d, 0x2e, 0x64,
	0x62, 0x2e, 0x53, 0x51, 0x4c, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x42, 0x23, 0x5a, 0x21, 0x70,
	0x68, 0x6f, 0x74, 0x6f, 0x67, 0x72, 0x61, 0x70, 0x68, 0x65, 0x72, 0x2f, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_protobuf_db_db_proto_rawDescOnce sync.Once
	file_internal_protobuf_db_db_proto_rawDescData = file_internal_protobuf_db_db_proto_rawDesc
)

func file_internal_protobuf_db_db_proto_rawDescGZIP() []byte {
	file_internal_protobuf_db_db_proto_rawDescOnce.Do(func() {
		file_internal_protobuf_db_db_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_protobuf_db_db_proto_rawDescData)
	})
	return file_internal_protobuf_db_db_proto_rawDescData
}

var file_internal_protobuf_db_db_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_internal_protobuf_db_db_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_internal_protobuf_db_db_proto_goTypes = []interface{}{
	(SQLJoin_JoinType)(0),   // 0: db.SQLJoin.JoinType
	(SQLResult_Result)(0),   // 1: db.SQLResult.Result
	(*SQLOption)(nil),       // 2: db.SQLOption
	(*SQLJoin)(nil),         // 3: db.SQLJoin
	(*SQLResult)(nil),       // 4: db.SQLResult
	(*SQLInsertParams)(nil), // 5: db.SQLInsertParams
	(*SQLUpdateParams)(nil), // 6: db.SQLUpdateParams
	(*SQLDeleteParams)(nil), // 7: db.SQLDeleteParams
	(*SQLSelectParams)(nil), // 8: db.SQLSelectParams
	nil,                     // 9: db.SQLUpdateParams.CouplesEntry
	(*any.Any)(nil),         // 10: google.protobuf.Any
}
var file_internal_protobuf_db_db_proto_depIdxs = []int32{
	10, // 0: db.SQLOption.args:type_name -> google.protobuf.Any
	0,  // 1: db.SQLJoin.joinType:type_name -> db.SQLJoin.JoinType
	10, // 2: db.SQLJoin.args:type_name -> google.protobuf.Any
	1,  // 3: db.SQLResult.result:type_name -> db.SQLResult.Result
	10, // 4: db.SQLResult.data:type_name -> google.protobuf.Any
	10, // 5: db.SQLInsertParams.values:type_name -> google.protobuf.Any
	9,  // 6: db.SQLUpdateParams.couples:type_name -> db.SQLUpdateParams.CouplesEntry
	2,  // 7: db.SQLUpdateParams.options:type_name -> db.SQLOption
	2,  // 8: db.SQLDeleteParams.options:type_name -> db.SQLOption
	2,  // 9: db.SQLSelectParams.options:type_name -> db.SQLOption
	3,  // 10: db.SQLSelectParams.joins:type_name -> db.SQLJoin
	10, // 11: db.SQLSelectParams.args:type_name -> google.protobuf.Any
	5,  // 12: db.DB.Create:input_type -> db.SQLInsertParams
	6,  // 13: db.DB.Update:input_type -> db.SQLUpdateParams
	7,  // 14: db.DB.Delete:input_type -> db.SQLDeleteParams
	8,  // 15: db.DB.Select:input_type -> db.SQLSelectParams
	4,  // 16: db.DB.Create:output_type -> db.SQLResult
	4,  // 17: db.DB.Update:output_type -> db.SQLResult
	4,  // 18: db.DB.Delete:output_type -> db.SQLResult
	4,  // 19: db.DB.Select:output_type -> db.SQLResult
	16, // [16:20] is the sub-list for method output_type
	12, // [12:16] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_internal_protobuf_db_db_proto_init() }
func file_internal_protobuf_db_db_proto_init() {
	if File_internal_protobuf_db_db_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_protobuf_db_db_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SQLOption); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_protobuf_db_db_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SQLJoin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_protobuf_db_db_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SQLResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_protobuf_db_db_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SQLInsertParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_protobuf_db_db_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SQLUpdateParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_protobuf_db_db_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SQLDeleteParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_protobuf_db_db_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SQLSelectParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_protobuf_db_db_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_protobuf_db_db_proto_goTypes,
		DependencyIndexes: file_internal_protobuf_db_db_proto_depIdxs,
		EnumInfos:         file_internal_protobuf_db_db_proto_enumTypes,
		MessageInfos:      file_internal_protobuf_db_db_proto_msgTypes,
	}.Build()
	File_internal_protobuf_db_db_proto = out.File
	file_internal_protobuf_db_db_proto_rawDesc = nil
	file_internal_protobuf_db_db_proto_goTypes = nil
	file_internal_protobuf_db_db_proto_depIdxs = nil
}
